//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.SiteminderWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.opentravel.org/OTA/2003/05", ConfigurationName="SiteminderWCF.IXMLData")]
    public interface IXMLData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentravel.org/OTA/2003/05/IXMLData/About", ReplyAction="http://www.opentravel.org/OTA/2003/05/IXMLData/AboutResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApplication1.SiteminderWCF.SiteMinderVersionResponse About();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opentravel.org/OTA/2003/05/IXMLData/About", ReplyAction="http://www.opentravel.org/OTA/2003/05/IXMLData/AboutResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.SiteminderWCF.SiteMinderVersionResponse> AboutAsync();
        
        // CODEGEN: Generating message contract since the operation HotelAvailRQ is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.siteminder.com.au/siteconnect/HotelAvailRQ", ReplyAction="http://www.opentravel.org/OTA/2003/05/IXMLData/HotelAvailRQResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApplication1.SiteminderWCF.OTAResponse HotelAvailRQ(ConsoleApplication1.SiteminderWCF.OTARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.siteminder.com.au/siteconnect/HotelAvailRQ", ReplyAction="http://www.opentravel.org/OTA/2003/05/IXMLData/HotelAvailRQResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.SiteminderWCF.OTAResponse> HotelAvailRQAsync(ConsoleApplication1.SiteminderWCF.OTARequest request);
        
        // CODEGEN: Generating message contract since the operation HotelAvailNotifRQ is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.siteminder.com.au/siteconnect/HotelAvailNotifRQ", ReplyAction="http://www.siteminder.com.au/siteconnect/HotelAvailNotifRS")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApplication1.SiteminderWCF.OTAHotelAvailNotifRS HotelAvailNotifRQ(ConsoleApplication1.SiteminderWCF.OTAHotelAvailPush request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.siteminder.com.au/siteconnect/HotelAvailNotifRQ", ReplyAction="http://www.siteminder.com.au/siteconnect/HotelAvailNotifRS")]
        System.Threading.Tasks.Task<ConsoleApplication1.SiteminderWCF.OTAHotelAvailNotifRS> HotelAvailNotifRQAsync(ConsoleApplication1.SiteminderWCF.OTAHotelAvailPush request);
        
        // CODEGEN: Generating message contract since the operation HotelRateAmountNotifRQ is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.siteminder.com.au/siteconnect/HotelRateAmountNotifRQ", ReplyAction="http://www.siteminder.com.au/siteconnect/HotelRateAmountNotifRS")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleApplication1.SiteminderWCF.OTAHotelRateAmountNotifRS HotelRateAmountNotifRQ(ConsoleApplication1.SiteminderWCF.OTAHotelRateAmountPush request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.siteminder.com.au/siteconnect/HotelRateAmountNotifRQ", ReplyAction="http://www.siteminder.com.au/siteconnect/HotelRateAmountNotifRS")]
        System.Threading.Tasks.Task<ConsoleApplication1.SiteminderWCF.OTAHotelRateAmountNotifRS> HotelRateAmountNotifRQAsync(ConsoleApplication1.SiteminderWCF.OTAHotelRateAmountPush request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class SiteMinderVersionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceInfo serviceResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public serviceInfo ServiceResponse {
            get {
                return this.serviceResponseField;
            }
            set {
                this.serviceResponseField = value;
                this.RaisePropertyChanged("ServiceResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class serviceInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceNameField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("ServiceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class OTA_HotelRateAmountNotifRS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Success successField;
        
        private string versionField;
        
        private string echoTokenField;
        
        private string timeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Success Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EchoToken {
            get {
                return this.echoTokenField;
            }
            set {
                this.echoTokenField = value;
                this.RaisePropertyChanged("EchoToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class Success : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class RateDescription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class BaseByGuestAmt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ageQualifyingCodeField;
        
        private string amountAfterTaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AgeQualifyingCode {
            get {
                return this.ageQualifyingCodeField;
            }
            set {
                this.ageQualifyingCodeField = value;
                this.RaisePropertyChanged("AgeQualifyingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AmountAfterTax {
            get {
                return this.amountAfterTaxField;
            }
            set {
                this.amountAfterTaxField = value;
                this.RaisePropertyChanged("AmountAfterTax");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class BaseByGuestAmts : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BaseByGuestAmt baseByGuestAmtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BaseByGuestAmt BaseByGuestAmt {
            get {
                return this.baseByGuestAmtField;
            }
            set {
                this.baseByGuestAmtField = value;
                this.RaisePropertyChanged("BaseByGuestAmt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class Rate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BaseByGuestAmts baseByGuestAmtsField;
        
        private RateDescription rateDescriptionField;
        
        private string ageQualifyingCodeField;
        
        private string amountAfterTaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BaseByGuestAmts BaseByGuestAmts {
            get {
                return this.baseByGuestAmtsField;
            }
            set {
                this.baseByGuestAmtsField = value;
                this.RaisePropertyChanged("BaseByGuestAmts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RateDescription RateDescription {
            get {
                return this.rateDescriptionField;
            }
            set {
                this.rateDescriptionField = value;
                this.RaisePropertyChanged("RateDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AgeQualifyingCode {
            get {
                return this.ageQualifyingCodeField;
            }
            set {
                this.ageQualifyingCodeField = value;
                this.RaisePropertyChanged("AgeQualifyingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AmountAfterTax {
            get {
                return this.amountAfterTaxField;
            }
            set {
                this.amountAfterTaxField = value;
                this.RaisePropertyChanged("AmountAfterTax");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class Rates : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Rate rateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Rate Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
                this.RaisePropertyChanged("Rate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class RateAmountMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatusApplicationControl statusApplicationControlField;
        
        private Rates ratesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusApplicationControl StatusApplicationControl {
            get {
                return this.statusApplicationControlField;
            }
            set {
                this.statusApplicationControlField = value;
                this.RaisePropertyChanged("StatusApplicationControl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Rates Rates {
            get {
                return this.ratesField;
            }
            set {
                this.ratesField = value;
                this.RaisePropertyChanged("Rates");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class StatusApplicationControl : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string startField;
        
        private string endField;
        
        private string invTypeCodeField;
        
        private string ratePlanCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("Start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("End");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InvTypeCode {
            get {
                return this.invTypeCodeField;
            }
            set {
                this.invTypeCodeField = value;
                this.RaisePropertyChanged("InvTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RatePlanCode {
            get {
                return this.ratePlanCodeField;
            }
            set {
                this.ratePlanCodeField = value;
                this.RaisePropertyChanged("RatePlanCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class RateAmountMessages : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RateAmountMessage rateAmountMessageField;
        
        private string hotelCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RateAmountMessage RateAmountMessage {
            get {
                return this.rateAmountMessageField;
            }
            set {
                this.rateAmountMessageField = value;
                this.RaisePropertyChanged("RateAmountMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HotelCode {
            get {
                return this.hotelCodeField;
            }
            set {
                this.hotelCodeField = value;
                this.RaisePropertyChanged("HotelCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class OTA_HotelRateAmountNotifRQ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RateAmountMessages rateAmountMessagesField;
        
        private string versionField;
        
        private string timeStampField;
        
        private string echoTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RateAmountMessages RateAmountMessages {
            get {
                return this.rateAmountMessagesField;
            }
            set {
                this.rateAmountMessagesField = value;
                this.RaisePropertyChanged("RateAmountMessages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EchoToken {
            get {
                return this.echoTokenField;
            }
            set {
                this.echoTokenField = value;
                this.RaisePropertyChanged("EchoToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class OTA_HotelAvailNotifRS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Success successField;
        
        private string versionField;
        
        private string echoTokenField;
        
        private string timeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Success Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EchoToken {
            get {
                return this.echoTokenField;
            }
            set {
                this.echoTokenField = value;
                this.RaisePropertyChanged("EchoToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class AvailStatusMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatusApplicationControl statusApplicationControlField;
        
        private string bookingLimitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusApplicationControl StatusApplicationControl {
            get {
                return this.statusApplicationControlField;
            }
            set {
                this.statusApplicationControlField = value;
                this.RaisePropertyChanged("StatusApplicationControl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BookingLimit {
            get {
                return this.bookingLimitField;
            }
            set {
                this.bookingLimitField = value;
                this.RaisePropertyChanged("BookingLimit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class AvailStatusMessages : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AvailStatusMessage availStatusMessageField;
        
        private string hotelCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AvailStatusMessage AvailStatusMessage {
            get {
                return this.availStatusMessageField;
            }
            set {
                this.availStatusMessageField = value;
                this.RaisePropertyChanged("AvailStatusMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HotelCode {
            get {
                return this.hotelCodeField;
            }
            set {
                this.hotelCodeField = value;
                this.RaisePropertyChanged("HotelCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class OTA_HotelAvailNotifRQ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AvailStatusMessages availStatusMessagesField;
        
        private string versionField;
        
        private string timeStampField;
        
        private string echoTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AvailStatusMessages AvailStatusMessages {
            get {
                return this.availStatusMessagesField;
            }
            set {
                this.availStatusMessagesField = value;
                this.RaisePropertyChanged("AvailStatusMessages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EchoToken {
            get {
                return this.echoTokenField;
            }
            set {
                this.echoTokenField = value;
                this.RaisePropertyChanged("EchoToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class RatePlanDescription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string textField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class RatePlan : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RatePlanDescription ratePlanDescriptionField;
        
        private string ratePlanCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RatePlanDescription RatePlanDescription {
            get {
                return this.ratePlanDescriptionField;
            }
            set {
                this.ratePlanDescriptionField = value;
                this.RaisePropertyChanged("RatePlanDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RatePlanCode {
            get {
                return this.ratePlanCodeField;
            }
            set {
                this.ratePlanCodeField = value;
                this.RaisePropertyChanged("RatePlanCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class RoomDescription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string textField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class RoomType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RoomDescription roomDescriptionField;
        
        private string roomTypeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RoomDescription RoomDescription {
            get {
                return this.roomDescriptionField;
            }
            set {
                this.roomDescriptionField = value;
                this.RaisePropertyChanged("RoomDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RoomTypeCode {
            get {
                return this.roomTypeCodeField;
            }
            set {
                this.roomTypeCodeField = value;
                this.RaisePropertyChanged("RoomTypeCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class RoomStay : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RoomType[] roomTypesField;
        
        private RatePlan[] ratePlansField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public RoomType[] RoomTypes {
            get {
                return this.roomTypesField;
            }
            set {
                this.roomTypesField = value;
                this.RaisePropertyChanged("RoomTypes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public RatePlan[] RatePlans {
            get {
                return this.ratePlansField;
            }
            set {
                this.ratePlansField = value;
                this.RaisePropertyChanged("RatePlans");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class OTA_HotelAvailRS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Success successField;
        
        private RoomStay[] roomStaysField;
        
        private string versionField;
        
        private string echoTokenField;
        
        private string timeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Success Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public RoomStay[] RoomStays {
            get {
                return this.roomStaysField;
            }
            set {
                this.roomStaysField = value;
                this.RaisePropertyChanged("RoomStays");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EchoToken {
            get {
                return this.echoTokenField;
            }
            set {
                this.echoTokenField = value;
                this.RaisePropertyChanged("EchoToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class HotelRef : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hotelCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HotelCode {
            get {
                return this.hotelCodeField;
            }
            set {
                this.hotelCodeField = value;
                this.RaisePropertyChanged("HotelCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class Criterion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HotelRef hotelRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HotelRef HotelRef {
            get {
                return this.hotelRefField;
            }
            set {
                this.hotelRefField = value;
                this.RaisePropertyChanged("HotelRef");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class HotelSearchCriteria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Criterion criterionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Criterion Criterion {
            get {
                return this.criterionField;
            }
            set {
                this.criterionField = value;
                this.RaisePropertyChanged("Criterion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class AvailRequestSegment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HotelSearchCriteria hotelSearchCriteriaField;
        
        private string availReqTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HotelSearchCriteria HotelSearchCriteria {
            get {
                return this.hotelSearchCriteriaField;
            }
            set {
                this.hotelSearchCriteriaField = value;
                this.RaisePropertyChanged("HotelSearchCriteria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AvailReqType {
            get {
                return this.availReqTypeField;
            }
            set {
                this.availReqTypeField = value;
                this.RaisePropertyChanged("AvailReqType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class AvailRequestSegments : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AvailRequestSegment availRequestSegmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AvailRequestSegment AvailRequestSegment {
            get {
                return this.availRequestSegmentField;
            }
            set {
                this.availRequestSegmentField = value;
                this.RaisePropertyChanged("AvailRequestSegment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class OTA_HotelAvailRQ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AvailRequestSegments availRequestSegmentsField;
        
        private string versionField;
        
        private string echoTokenField;
        
        private string timeStampField;
        
        private bool availRatesOnlyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AvailRequestSegments AvailRequestSegments {
            get {
                return this.availRequestSegmentsField;
            }
            set {
                this.availRequestSegmentsField = value;
                this.RaisePropertyChanged("AvailRequestSegments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EchoToken {
            get {
                return this.echoTokenField;
            }
            set {
                this.echoTokenField = value;
                this.RaisePropertyChanged("EchoToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AvailRatesOnly {
            get {
                return this.availRatesOnlyField;
            }
            set {
                this.availRatesOnlyField = value;
                this.RaisePropertyChanged("AvailRatesOnly");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OTARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opentravel.org/OTA/2003/05", Order=0)]
        public ConsoleApplication1.SiteminderWCF.OTA_HotelAvailRQ OTA_HotelAvailRQ;
        
        public OTARequest() {
        }
        
        public OTARequest(ConsoleApplication1.SiteminderWCF.OTA_HotelAvailRQ OTA_HotelAvailRQ) {
            this.OTA_HotelAvailRQ = OTA_HotelAvailRQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OTAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opentravel.org/OTA/2003/05", Order=0)]
        public ConsoleApplication1.SiteminderWCF.OTA_HotelAvailRS OTA_HotelAvailRS;
        
        public OTAResponse() {
        }
        
        public OTAResponse(ConsoleApplication1.SiteminderWCF.OTA_HotelAvailRS OTA_HotelAvailRS) {
            this.OTA_HotelAvailRS = OTA_HotelAvailRS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OTAHotelAvailPush {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opentravel.org/OTA/2003/05", Order=0)]
        public ConsoleApplication1.SiteminderWCF.OTA_HotelAvailNotifRQ OTA_HotelAvailNotifRQ;
        
        public OTAHotelAvailPush() {
        }
        
        public OTAHotelAvailPush(ConsoleApplication1.SiteminderWCF.OTA_HotelAvailNotifRQ OTA_HotelAvailNotifRQ) {
            this.OTA_HotelAvailNotifRQ = OTA_HotelAvailNotifRQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OTAHotelAvailNotifRS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opentravel.org/OTA/2003/05", Order=0)]
        public ConsoleApplication1.SiteminderWCF.OTA_HotelAvailNotifRS OTA_HotelAvailNotifRS;
        
        public OTAHotelAvailNotifRS() {
        }
        
        public OTAHotelAvailNotifRS(ConsoleApplication1.SiteminderWCF.OTA_HotelAvailNotifRS OTA_HotelAvailNotifRS) {
            this.OTA_HotelAvailNotifRS = OTA_HotelAvailNotifRS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OTAHotelRateAmountPush {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opentravel.org/OTA/2003/05", Order=0)]
        public ConsoleApplication1.SiteminderWCF.OTA_HotelRateAmountNotifRQ OTA_HotelRateAmountNotifRQ;
        
        public OTAHotelRateAmountPush() {
        }
        
        public OTAHotelRateAmountPush(ConsoleApplication1.SiteminderWCF.OTA_HotelRateAmountNotifRQ OTA_HotelRateAmountNotifRQ) {
            this.OTA_HotelRateAmountNotifRQ = OTA_HotelRateAmountNotifRQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OTAHotelRateAmountNotifRS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opentravel.org/OTA/2003/05", Order=0)]
        public ConsoleApplication1.SiteminderWCF.OTA_HotelRateAmountNotifRS OTA_HotelRateAmountNotifRS;
        
        public OTAHotelRateAmountNotifRS() {
        }
        
        public OTAHotelRateAmountNotifRS(ConsoleApplication1.SiteminderWCF.OTA_HotelRateAmountNotifRS OTA_HotelRateAmountNotifRS) {
            this.OTA_HotelRateAmountNotifRS = OTA_HotelRateAmountNotifRS;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXMLDataChannel : ConsoleApplication1.SiteminderWCF.IXMLData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XMLDataClient : System.ServiceModel.ClientBase<ConsoleApplication1.SiteminderWCF.IXMLData>, ConsoleApplication1.SiteminderWCF.IXMLData {
        
        public XMLDataClient() {
        }
        
        public XMLDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XMLDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApplication1.SiteminderWCF.SiteMinderVersionResponse About() {
            return base.Channel.About();
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.SiteminderWCF.SiteMinderVersionResponse> AboutAsync() {
            return base.Channel.AboutAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.SiteminderWCF.OTAResponse ConsoleApplication1.SiteminderWCF.IXMLData.HotelAvailRQ(ConsoleApplication1.SiteminderWCF.OTARequest request) {
            return base.Channel.HotelAvailRQ(request);
        }
        
        public ConsoleApplication1.SiteminderWCF.OTA_HotelAvailRS HotelAvailRQ(ConsoleApplication1.SiteminderWCF.OTA_HotelAvailRQ OTA_HotelAvailRQ) {
            ConsoleApplication1.SiteminderWCF.OTARequest inValue = new ConsoleApplication1.SiteminderWCF.OTARequest();
            inValue.OTA_HotelAvailRQ = OTA_HotelAvailRQ;
            ConsoleApplication1.SiteminderWCF.OTAResponse retVal = ((ConsoleApplication1.SiteminderWCF.IXMLData)(this)).HotelAvailRQ(inValue);
            return retVal.OTA_HotelAvailRS;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.SiteminderWCF.OTAResponse> ConsoleApplication1.SiteminderWCF.IXMLData.HotelAvailRQAsync(ConsoleApplication1.SiteminderWCF.OTARequest request) {
            return base.Channel.HotelAvailRQAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.SiteminderWCF.OTAResponse> HotelAvailRQAsync(ConsoleApplication1.SiteminderWCF.OTA_HotelAvailRQ OTA_HotelAvailRQ) {
            ConsoleApplication1.SiteminderWCF.OTARequest inValue = new ConsoleApplication1.SiteminderWCF.OTARequest();
            inValue.OTA_HotelAvailRQ = OTA_HotelAvailRQ;
            return ((ConsoleApplication1.SiteminderWCF.IXMLData)(this)).HotelAvailRQAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.SiteminderWCF.OTAHotelAvailNotifRS ConsoleApplication1.SiteminderWCF.IXMLData.HotelAvailNotifRQ(ConsoleApplication1.SiteminderWCF.OTAHotelAvailPush request) {
            return base.Channel.HotelAvailNotifRQ(request);
        }
        
        public ConsoleApplication1.SiteminderWCF.OTA_HotelAvailNotifRS HotelAvailNotifRQ(ConsoleApplication1.SiteminderWCF.OTA_HotelAvailNotifRQ OTA_HotelAvailNotifRQ) {
            ConsoleApplication1.SiteminderWCF.OTAHotelAvailPush inValue = new ConsoleApplication1.SiteminderWCF.OTAHotelAvailPush();
            inValue.OTA_HotelAvailNotifRQ = OTA_HotelAvailNotifRQ;
            ConsoleApplication1.SiteminderWCF.OTAHotelAvailNotifRS retVal = ((ConsoleApplication1.SiteminderWCF.IXMLData)(this)).HotelAvailNotifRQ(inValue);
            return retVal.OTA_HotelAvailNotifRS;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.SiteminderWCF.OTAHotelAvailNotifRS> ConsoleApplication1.SiteminderWCF.IXMLData.HotelAvailNotifRQAsync(ConsoleApplication1.SiteminderWCF.OTAHotelAvailPush request) {
            return base.Channel.HotelAvailNotifRQAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.SiteminderWCF.OTAHotelAvailNotifRS> HotelAvailNotifRQAsync(ConsoleApplication1.SiteminderWCF.OTA_HotelAvailNotifRQ OTA_HotelAvailNotifRQ) {
            ConsoleApplication1.SiteminderWCF.OTAHotelAvailPush inValue = new ConsoleApplication1.SiteminderWCF.OTAHotelAvailPush();
            inValue.OTA_HotelAvailNotifRQ = OTA_HotelAvailNotifRQ;
            return ((ConsoleApplication1.SiteminderWCF.IXMLData)(this)).HotelAvailNotifRQAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.SiteminderWCF.OTAHotelRateAmountNotifRS ConsoleApplication1.SiteminderWCF.IXMLData.HotelRateAmountNotifRQ(ConsoleApplication1.SiteminderWCF.OTAHotelRateAmountPush request) {
            return base.Channel.HotelRateAmountNotifRQ(request);
        }
        
        public ConsoleApplication1.SiteminderWCF.OTA_HotelRateAmountNotifRS HotelRateAmountNotifRQ(ConsoleApplication1.SiteminderWCF.OTA_HotelRateAmountNotifRQ OTA_HotelRateAmountNotifRQ) {
            ConsoleApplication1.SiteminderWCF.OTAHotelRateAmountPush inValue = new ConsoleApplication1.SiteminderWCF.OTAHotelRateAmountPush();
            inValue.OTA_HotelRateAmountNotifRQ = OTA_HotelRateAmountNotifRQ;
            ConsoleApplication1.SiteminderWCF.OTAHotelRateAmountNotifRS retVal = ((ConsoleApplication1.SiteminderWCF.IXMLData)(this)).HotelRateAmountNotifRQ(inValue);
            return retVal.OTA_HotelRateAmountNotifRS;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.SiteminderWCF.OTAHotelRateAmountNotifRS> ConsoleApplication1.SiteminderWCF.IXMLData.HotelRateAmountNotifRQAsync(ConsoleApplication1.SiteminderWCF.OTAHotelRateAmountPush request) {
            return base.Channel.HotelRateAmountNotifRQAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.SiteminderWCF.OTAHotelRateAmountNotifRS> HotelRateAmountNotifRQAsync(ConsoleApplication1.SiteminderWCF.OTA_HotelRateAmountNotifRQ OTA_HotelRateAmountNotifRQ) {
            ConsoleApplication1.SiteminderWCF.OTAHotelRateAmountPush inValue = new ConsoleApplication1.SiteminderWCF.OTAHotelRateAmountPush();
            inValue.OTA_HotelRateAmountNotifRQ = OTA_HotelRateAmountNotifRQ;
            return ((ConsoleApplication1.SiteminderWCF.IXMLData)(this)).HotelRateAmountNotifRQAsync(inValue);
        }
    }
}
